// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjc_EuZCkVUTZpqBelsbkK-nEc1lWbtq0',
    appId: '1:80343340802:web:941ab065dbfc7b8572141b',
    messagingSenderId: '80343340802',
    projectId: 'ns-mis-lab2',
    authDomain: 'ns-mis-lab2.firebaseapp.com',
    storageBucket: 'ns-mis-lab2.firebasestorage.app',
    measurementId: 'G-JBN05V7BXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiX-AOBkIgQstk_XDf54ybczO0SAS1dK0',
    appId: '1:80343340802:android:b934ff52c716858072141b',
    messagingSenderId: '80343340802',
    projectId: 'ns-mis-lab2',
    storageBucket: 'ns-mis-lab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEBDRAi1gnknJ--AG8EXo2ycSvDKe1Az8',
    appId: '1:80343340802:ios:edcfd8e1b566191072141b',
    messagingSenderId: '80343340802',
    projectId: 'ns-mis-lab2',
    storageBucket: 'ns-mis-lab2.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEBDRAi1gnknJ--AG8EXo2ycSvDKe1Az8',
    appId: '1:80343340802:ios:edcfd8e1b566191072141b',
    messagingSenderId: '80343340802',
    projectId: 'ns-mis-lab2',
    storageBucket: 'ns-mis-lab2.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjc_EuZCkVUTZpqBelsbkK-nEc1lWbtq0',
    appId: '1:80343340802:web:8967daa1635c6f9d72141b',
    messagingSenderId: '80343340802',
    projectId: 'ns-mis-lab2',
    authDomain: 'ns-mis-lab2.firebaseapp.com',
    storageBucket: 'ns-mis-lab2.firebasestorage.app',
    measurementId: 'G-QC3EM95QJ9',
  );
}
